apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: {{ .Values.nginx.name }}  
        image: {{ .Values.nginx.image }} 
        ports:
        - containerPort: {{ .Values.nginx.port }}
